//
// Created by 86156 on 2021-11-18.
//

#ifndef COMPILATIONPRINCPLE_INTERPRETATION_EXECUTION_H
#define COMPILATIONPRINCPLE_INTERPRETATION_EXECUTION_H


class Interpretation_execution {

};


#endif //COMPILATIONPRINCPLE_INTERPRETATION_EXECUTION_H
