//
// Created by 86156 on 2021-11-18.
//

#ifndef COMPILATIONPRINCPLE_SEMANTIC_ANALYSIS_H
#define COMPILATIONPRINCPLE_SEMANTIC_ANALYSIS_H


class Semantic_analysis {

};


#endif //COMPILATIONPRINCPLE_SEMANTIC_ANALYSIS_H
